spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: 1234


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug


#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      defer-datasource-initialization: true


#      datasource:
#        url: jdbc:h2:mem:test
#        username: sa
#  h2:
#    console:
#      enabled: true



jwt:
  issuer: test@test.com
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

