name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t spring-cicd . 
          docker tag spring-cicd songeunlee/spring-cicd:${GITHUB_SHA::7}
          docker push songeunlee/spring-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-125-102-45.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull songeunlee/spring-cicd:${GITHUB_SHA::7}
            docker tag songeunlee/spring-cicd:${GITHUB_SHA::7} spring-cicd
            docker stop server
            docker rm -f server
            docker run -d --name server -p 8080:8080 spring-cicd
